Add ReconcileNode function
kubedb/mariadb pull request #68
Opened 2021-05-04 09:46 UTC by spectro30

Signed-off-by: Md. Alif Biswas <alif@appscode.com>

2021-05-04 10:17 UTC, spectro30 commented
e2e test passed after the changes.

2021-05-04 10:19 UTC, kamolhasan commented on pkg/controller/secret.go
>  	authSecretName := db.Name + "-auth"
Use methods:

func (db *MariaDB) AuthSecretName() string {
 return NameWithSuffix(db.Name,"auth")
}

2021-05-04 10:21 UTC, kamolhasan requested changes
LGTM!

2021-05-05 05:26 UTC, spectro30 commented on pkg/controller/secret.go
>  	authSecretName := db.Name + "-auth"
added

2021-06-14 10:56 UTC, spectro30 commented
General e2e-test passed.

2021-06-15 08:56 UTC, kamolhasan approved these changes
LGTM!

2021-06-15 09:26 UTC, Emon46 submitted a review, later dismissed

2021-06-17 06:37 UTC, kamolhasan approved these changes
LGTM!

2021-06-17 06:38 UTC, merged