Limit Health Checker goroutines
kubedb/mariadb pull request #69
Opened 2021-05-22 09:25 UTC by spectro30

2021-05-22 09:36 UTC, spectro30 commented
**Merge this first**
https://github.com/kubedb/mariadb/pull/68

2021-06-15 08:40 UTC, spectro30 commented
e2e general test passed

2021-06-15 09:24 UTC, kamolhasan requested changes

2021-06-15 09:24 UTC, kamolhasan commented on pkg/controller/health.go
> +		if db.DeletionTimestamp != nil {
Also skip the health check for the halted dbs, `db.spec.halt==true`

2021-06-15 09:24 UTC, kamolhasan commented on pkg/controller/health.go
> +		go func() {
Send DB object as input parameter,

go func(db *api.MariaDB){
... ...
... ...
}(db)

2021-06-15 09:24 UTC, kamolhasan commented on pkg/controller/health.go
> +						klog.Warning("host is not online ", err.Error())
return from here, if an error occurs

2021-06-15 10:00 UTC, spectro30 commented on pkg/controller/health.go
> +		if db.DeletionTimestamp != nil {
added

2021-06-15 10:03 UTC, spectro30 commented on pkg/controller/health.go
> +		go func() {
added

2021-06-15 10:42 UTC, spectro30 commented on pkg/controller/health.go
> +						klog.Warning("host is not online ", err.Error())
fixed

2021-06-15 11:12 UTC, closed without merging